#!/usr/bin/env bash
# Shared by the android and ios drivers: build the root flow for this run from the NAV_* env
# the dispatcher exported (one `runFlow: level.yaml` per level — Maestro has no loops) and run
# it. bash 3.2 compatible (plain arrays only).
#
#   maestro_navigate <platform> <udid>      login (unless NAV_LOGIN_KIND=none or NAV_MANUAL_LOGIN=1) + levels
#   maestro_login    <platform> <udid>      login only
#
# Every `id:` in the flows is a Compose testTag / accessibility identifier; a list row must
# carry the same id on every row, with the text on its children.

set -u
MAESTRO_FLOWS="$(cd "$(dirname "${BASH_SOURCE[0]}")/flows" && pwd)"
MAESTRO_ARGS=()

_maestro_common_args() {
  MAESTRO_ARGS=(
    -e "APP_ID=$NAV_APP_ID"
    -e "LOGIN_BUTTON=${NAV_LOGIN_BUTTON:-}"
    -e "USERNAME_SEL=${NAV_LOGIN_USERNAME_SEL:-}"
    -e "PASSWORD_SEL=${NAV_LOGIN_PASSWORD_SEL:-}"
    -e "SUBMIT_SEL=${NAV_LOGIN_SUBMIT_SEL:-}"
    -e "READY_SEL=${NAV_READY_SEL:-}"
    -e "USERNAME=${NAV_USERNAME:-}"
    -e "PASSWORD=${NAV_PASSWORD:-}"
  )
}

_login_flow_file() {
  case "${NAV_LOGIN_KIND:-none}" in
    web-form) printf 'login_web_form.yaml' ;;
    native)   printf 'login_native.yaml' ;;
    *)        printf '' ;;
  esac
}

# Writes the generated root flow to a temp file (absolute `file:` paths to the templates)
# and prints its path.
_write_root_flow() {
  local out login i q qrx s r rd
  out="$(mktemp "${TMPDIR:-/tmp}/appnav-flow.XXXXXX.yaml")"
  login="$(_login_flow_file)"
  {
    printf '# Generated by drivers/maestro/run.sh for one run.\n'
    printf 'appId: ${APP_ID}\n---\n'
    printf -- '- launchApp:\n    appId: ${APP_ID}\n    stopApp: false\n    clearState: false\n    permissions:\n      all: allow\n'
    if [ -n "$login" ] && [ "${NAV_MANUAL_LOGIN:-0}" != 1 ]; then
      printf -- '- runFlow:\n    file: %s/%s\n' "$MAESTRO_FLOWS" "$login"
    elif [ -n "${NAV_READY_SEL:-}" ]; then
      printf -- '- extendedWaitUntil:\n    visible:\n      id: "%s"\n    timeout: 60000\n' "$NAV_READY_SEL"
    fi
    i=1
    while [ "$i" -le "${NAV_LEVEL_COUNT:-0}" ]; do
      eval "q=\${NAV_LEVEL_${i}_QUERY:-}"; eval "qrx=\${NAV_LEVEL_${i}_QUERY_RX:-}"
      eval "s=\${NAV_LEVEL_${i}_SEARCH:-}"; eval "r=\${NAV_LEVEL_${i}_ROW:-}"; eval "rd=\${NAV_LEVEL_${i}_READY:-}"
      printf -- '- runFlow:\n    file: %s/level.yaml\n    env:\n      SEARCH_SEL: "%s"\n      ROW_SEL: "%s"\n      READY_SEL: "%s"\n      QUERY: "%s"\n      QUERY_RX: "%s"\n' \
        "$MAESTRO_FLOWS" "$s" "$r" "$rd" "$q" "$qrx"
      i=$((i + 1))
    done
  } > "$out"
  printf '%s' "$out"
}

_maestro_run() {
  # $1 platform, $2 udid, $3 flow path; MAESTRO_ARGS carries the -e pairs
  local platform="$1" udid="$2" flow="$3" bin
  bin="$(find_maestro)"
  nav_log "maestro: $flow"
  # Global options go before the subcommand (picocli).
  MAESTRO_CLI_NO_ANALYTICS=1 "$bin" --platform "$platform" --udid "$udid" test "${MAESTRO_ARGS[@]}" "$flow"
}

maestro_navigate() {
  local flow rc
  flow="$(_write_root_flow)"
  _maestro_common_args
  if [ "${APPNAV_KEEP_FLOW:-0}" = 1 ]; then nav_log "generated flow kept at $flow"; fi
  set +e; _maestro_run "$1" "$2" "$flow"; rc=$?; set -e
  [ "${APPNAV_KEEP_FLOW:-0}" = 1 ] || rm -f "$flow"
  return "$rc"
}

maestro_login() {
  local login; login="$(_login_flow_file)"
  [ -n "$login" ] || { nav_log "login.kind is none — nothing to do"; return 0; }
  _maestro_common_args
  _maestro_run "$1" "$2" "$MAESTRO_FLOWS/$login"
}
